// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOQWCMLbSc2ie_6DHw4jow01nSRuCUCq0',
    appId: '1:556751661372:web:a602ca176a44e28831d639',
    messagingSenderId: '556751661372',
    projectId: 'yourflow-app',
    authDomain: 'yourflow-app.firebaseapp.com',
    storageBucket: 'yourflow-app.appspot.com',
    measurementId: 'G-2KY517PJYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZvJtOMRctrysqWBT46hNEDZhkP9b0MJI',
    appId: '1:1078170401994:android:2a168e2b0bcb9459e90833',
    messagingSenderId: '1078170401994',
    projectId: 'sf-dataflow',
    storageBucket: 'sf-dataflow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxJPAT1JDsH9F9xc6zSaINyDcmyt6D8dk',
    appId: '1:1078170401994:ios:ebc4a8ea7748d7b6e90833',
    messagingSenderId: '1078170401994',
    projectId: 'sf-dataflow',
    storageBucket: 'sf-dataflow.appspot.com',
    iosBundleId: 'com.sellersflow.yourflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxJPAT1JDsH9F9xc6zSaINyDcmyt6D8dk',
    appId: '1:1078170401994:ios:d605fd801879fe62e90833',
    messagingSenderId: '1078170401994',
    projectId: 'sf-dataflow',
    storageBucket: 'sf-dataflow.appspot.com',
    iosBundleId: 'com.sellersflow.yourflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMC3r16fO-EV74SUDNe-0K0p-a8Od6ESc',
    appId: '1:1078170401994:web:1af31988a9cf992fe90833',
    messagingSenderId: '1078170401994',
    projectId: 'sf-dataflow',
    authDomain: 'sf-dataflow.firebaseapp.com',
    storageBucket: 'sf-dataflow.appspot.com',
    measurementId: 'G-E41480NFFP',
  );
}
