// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOQWCMLbSc2ie_6DHw4jow01nSRuCUCq0',
    appId: '1:556751661372:web:a602ca176a44e28831d639',
    messagingSenderId: '556751661372',
    projectId: 'yourflow-app',
    authDomain: 'yourflow-app.firebaseapp.com',
    storageBucket: 'yourflow-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWJc6p9-kbbRnuEiwlGGShJMQmNYpJfsA',
    appId: '1:556751661372:android:2006e5f9d4dbf69631d639',
    messagingSenderId: '556751661372',
    projectId: 'yourflow-app',
    storageBucket: 'yourflow-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe23m82-16XCBvjLpoiz9KCY-0gMVn8kQ',
    appId: '1:556751661372:ios:e4f22bb415ed73c231d639',
    messagingSenderId: '556751661372',
    projectId: 'yourflow-app',
    storageBucket: 'yourflow-app.appspot.com',
    iosBundleId: 'com.avla.yourflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe23m82-16XCBvjLpoiz9KCY-0gMVn8kQ',
    appId: '1:556751661372:ios:e29aa9329b4d2cf431d639',
    messagingSenderId: '556751661372',
    projectId: 'yourflow-app',
    storageBucket: 'yourflow-app.appspot.com',
    iosBundleId: 'com.avlasolutions.yourflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOQWCMLbSc2ie_6DHw4jow01nSRuCUCq0',
    appId: '1:556751661372:web:4ed16bdb0e7ccb6331d639',
    messagingSenderId: '556751661372',
    projectId: 'yourflow-app',
    authDomain: 'yourflow-app.firebaseapp.com',
    storageBucket: 'yourflow-app.appspot.com',
  );
}
